#!/bin/bash
source /etc/shpkg.conf
source ~/.config/shpkg.conf

if (( $EUID == 0 )); then
    echo "running script"
    sudo /usr/local/share/repos/$1/sui.sh
    exit
fi

if [[ -f "~/.local/share/repos/$1/uui.sh" ]]
then
    echo "running script"
    ~/.local/share/repos/$1/uui.sh
    exit
fi

if [[ -f "/usr/local/share/repos/$1/uui.sh" ]]
then
    echo "running script"
    /usr/local/share/repos/$1/uui.sh
    exit
fi

echo "shpkg can't find uninstallation scripts"
