#!/bin/bash
source /etc/shpkg.conf
source ~/.config/shpkg.conf

USERUNINSTALLER=~/.local/share/repos/$1/$2/uui.sh
SYSTEMWIDEUNINSTALLER=/usr/local/share/repos/$1/$2/uui.sh
ROOTUNINSTALLER=/usr/local/share/repos/$1/$2/sui.sh

if (( $EUID == 0 )); then
    echo "running script"
    sudo source /usr/local/share/repos/$1/$2/sui.sh
    exit
fi

if [[ -f "$USERUNINSTALLER" ]]
then
    echo "running script"
    source ~/.local/share/repos/$1/$2/uui.sh
    exit
fi

if [[ -f "$SYSTEMWIDEUNINSTALLER" ]]
then
    echo "running script"
    source /usr/local/share/repos/$1/$2/uui.sh
    exit
fi

echo "shpkg can't find uninstallation scripts"
