#!/bin/bash
source /etc/shpkg.conf
source ~/.config/shpkg.conf

if (( $EUID == 0 )); then
    sudo mkdir /usr/local/share/repos/$1
    sudo git clone $2 /usr/local/share/repos/$1
    exit
fi

mkdir ~/.local/share/repos/$1
git clone $2 ~/.local/share/repos/$1
